version: '2.1'

services:
  registry:
    build: registry
    mem_limit: 350m
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  employee-api:
    build: employee-api
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  payroll-api:
    build: payroll-api
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  report-api:
    build: report-api
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      rabbitmq:
        condition: service_healthy
  mail-client:
    build: mail-client
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      rabbitmq:
        condition: service_healthy
  gateway:
    build: gateway
    mem_limit: 350m
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  rabbitmq:
    image: rabbitmq:3.7.8-management
    mem_limit: 350m
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10